import { ExperienceItem } from "@/types/experience";

export const experienceData: ExperienceItem[] = [
  {
    company: "Mobisys GmbH",
    role: "Test Automation Engineer",
    startDate: "2025-03-01",
    endDate: "2026-01-01",
    impact: [
      "Developed and maintained automated test suites using TypeScript, WebdriverIO, Cucumber, and Mocha",
      "Performed manual functional and regression testing across web and mobile interfaces",
      "Executed API integration testing, validating backend services and business logic",
      "Supported CI/CD pipelines, ensuring reliable automation execution across releases",
      "Collaborated with developers on defect analysis and root-cause investigation",
      "Maintained test traceability and reporting using Jira and Xray",
    ],
    techStack: [
      "TypeScript",
      "WebdriverIO",
      "Cucumber",
      "Mocha",
      "BrowserStack",
      "Jira",
      "Xray",
      "CI/CD",
      "API Testing",
    ],
  },
  {
    company: "LexisNexis",
    role: "Quality Test Engineer III",
    startDate: "2022-04-01",
    endDate: "2024-03-01",
    impact: [
      "Collaborated with engineering and product teams to identify testing needs, reducing production defects by 30%",
      "Led the implementation of a CI/CD pipeline, integrating automated tests to streamline deployment",
      "Mentored junior testers, improving team capability in both manual and automated testing",
      "Conducted UI & API test automation, unit test code review, and accessibility testing",
    ],
    techStack: [
      "Cypress",
      "Selenium",
      "Cucumber",
      "Xunit",
      "Jenkins",
      "Azure DevOps",
      "AWS",
      ".NET Core",
      "ASP.NET",
      "C#",
      "AngularJS",
      "React.js",
    ],
  },
  {
    company: "Future Front",
    role: "Contract Software Engineer",
    startDate: "2022-01-01",
    endDate: "2022-04-01",
    impact: [
      "Implemented cross-platform testing strategies ensuring seamless integration across applications and services",
    ],
    techStack: [
      ".NET",
      "ASP.NET",
      "C#",
      "Android Development",
      "Python",
      "DevOps",
      "Sage 300",
      "Odoo ERP",
    ],
  },
  {
    company: "GLI Africa",
    role: "Test Engineer I",
    startDate: "2021-09-01",
    endDate: "2022-01-01",
    impact: [
      "Introduced automated testing tools, significantly reducing manual testing time and improving accuracy",
      "Performed source code review, error/fault event handling, and regulatory compliance testing",
      "Conducted accounting accuracy verification and hardware testing",
    ],
    techStack: [
      "Source Code Review",
      "Regulatory Compliance Testing",
      "Communication Protocol Testing",
      "Hardware Testing",
    ],
  },
  {
    company: "SYSPRO Africa",
    role: "Junior Developer",
    startDate: "2020-01-01",
    endDate: "2021-09-01",
    impact: [
      "Developed solutions to extend functionality and capability of the standard ERP solution",
      "Performed requirements analysis, software architecture design, coding, testing and deployment",
    ],
    techStack: [".NET", "ASP.NET", "C#", "VBScript", "DevOps"],
  },
  {
    company: "SYSPRO Africa",
    role: "Intern – SYSPRO Internship Program",
    startDate: "2019-01-01",
    endDate: "2020-01-01",
    impact: [
      "Learned Enterprise Resource Planning concepts across supply chain, manufacturing, and distribution",
    ],
    techStack: [
      "SYSPRO 8",
      "ERP",
      "Supply Chain",
      "Manufacturing",
      "Distribution",
    ],
  },
  {
    company: "Future Front Web",
    role: "Freelance Web Developer",
    startDate: "2017-06-01",
    endDate: "2019-01-01",
    impact: [
      "Collaborated with clients to deliver tailored solutions, exceeding expectations in functionality and usability",
    ],
    techStack: ["PHP", "HTML", "CSS", "Bootstrap", "JavaScript", "jQuery"],
  },
];
