import { ProfileData } from "@/types/profile";

export const profileData: ProfileData = {
  name: "Itumeleng Phalafala",
  title: "QA Engineer & Developer",
  tagline:
    "Building reliable, high-quality software through test automation, CI/CD, and modern development practices.",
  cvUrl: "/Itumeleng_Phalafala_CV.pdf",
  location: "Johannesburg, South Africa",
  email: "ituphala@gmail.com",
  linkedIn: "https://www.linkedin.com/in/itumeleng-phalafala",
  summary:
    "Quality Assurance Engineer with 6+ years of experience across software development and quality engineering, specialising in manual and automated testing for web, mobile, and API-driven systems. Strong technical background with hands-on experience in test automation, CI/CD pipelines, and debugging complex systems. Comfortable working in fast-paced, enterprise and product-driven environments, collaborating closely with developers, product owners, and stakeholders to ensure high-quality, reliable software delivery.",
  coreCompetencies: [
    "Test Strategy & Planning",
    "Agile & CI/CD Environments",
    "Defect Management & Debugging",
    "Test Automation",
    "API & Integration Testing",
    "Cross-Browser & Cross-Device Testing",
    "Cloud & DevOps Exposure",
  ],
  languages: [
    "C#",
    "TypeScript",
    "Python",
    "SQL",
    "JavaScript",
    "PHP",
    "HTML5",
    "CSS",
    "Solidity",
  ],
  frameworks: [
    ".NET",
    "ASP.NET",
    "AngularJS",
    "Node.js",
    "React.js",
    "Cypress",
    "Selenium",
    "WebdriverIO",
    "Cucumber",
    "Mocha",
    "Chai",
    "Karate",
  ],
  tools: [
    "Azure DevOps",
    "AWS",
    "Jenkins",
    "Jira",
    "Xray",
    "Postman",
    "Mockoon",
    "BrowserStack",
    "Git",
    "VS Code",
    "PyCharm",
  ],
  experience: [
    {
      company: "Mobisys GmbH",
      location: "Walldorf, Germany",
      role: "Test Automation Engineer",
      period: "March 2025 – January 2026",
      description:
        "Worked on an enterprise-grade platform enabling developers to rapidly build and customise SAP-based applications for multiple business use cases.",
      highlights: [
        "Developed and maintained automated test suites using TypeScript, WebdriverIO, Cucumber, and Mocha",
        "Performed manual functional and regression testing across web and mobile interfaces",
        "Executed API integration testing, validating backend services and business logic",
        "Supported CI/CD pipelines, ensuring reliable automation execution across releases",
        "Collaborated with developers on defect analysis and root-cause investigation",
        "Maintained test traceability and reporting using Jira and Xray",
      ],
      technologies: [
        "TypeScript",
        "WebdriverIO",
        "Cucumber",
        "Mocha",
        "BrowserStack",
        "Jira",
        "Xray",
        "CI/CD",
        "API Testing",
      ],
    },
    {
      company: "LexisNexis",
      location: "Woodmead, South Africa",
      role: "Quality Test Engineer III",
      period: "April 2022 – March 2024",
      description:
        "Developed and maintained automated test scripts, ensuring coverage for all critical paths in the software.",
      highlights: [
        "Collaborated with engineering and product teams to identify testing needs, reducing production defects by 30%",
        "Led the implementation of a CI/CD pipeline, integrating automated tests to streamline deployment",
        "Mentored junior testers, improving team capability in both manual and automated testing",
        "Conducted UI & API test automation, unit test code review, and accessibility testing",
      ],
      technologies: [
        "Cypress",
        "Selenium",
        "Cucumber",
        "Xunit",
        "Jenkins",
        "Azure DevOps",
        "AWS",
        ".NET Core",
        "ASP.NET",
        "C#",
        "AngularJS",
        "React.js",
      ],
    },
    {
      company: "Future Front",
      location: "Johannesburg, South Africa",
      role: "Contract Software Engineer",
      period: "January 2022 – April 2022",
      description:
        "Developed custom software solutions, focusing on test automation and quality assurance within client projects.",
      highlights: [
        "Implemented cross-platform testing strategies ensuring seamless integration across applications and services",
      ],
      technologies: [
        ".NET",
        "ASP.NET",
        "C#",
        "Android Development",
        "Python",
        "DevOps",
        "Sage 300",
        "Odoo ERP",
      ],
    },
    {
      company: "GLI Africa",
      location: "Midrand, South Africa",
      role: "Test Engineer I",
      period: "September 2021 – January 2022",
      description:
        "Conducted comprehensive testing of gaming and gambling systems, ensuring compliance with regulatory standards.",
      highlights: [
        "Introduced automated testing tools, significantly reducing manual testing time and improving accuracy",
        "Performed source code review, error/fault event handling, and regulatory compliance testing",
        "Conducted accounting accuracy verification and hardware testing",
      ],
      technologies: [
        "Source Code Review",
        "Regulatory Compliance Testing",
        "Communication Protocol Testing",
        "Hardware Testing",
      ],
    },
    {
      company: "SYSPRO Africa",
      location: "Sunninghill, South Africa",
      role: "Junior Developer",
      period: "January 2020 – September 2021",
      description:
        "Responsible for designing, developing and testing solutions that cater to customer ERP requirements.",
      highlights: [
        "Developed solutions to extend functionality and capability of the standard ERP solution",
        "Performed requirements analysis, software architecture design, coding, testing and deployment",
      ],
      technologies: [".NET", "ASP.NET", "C#", "VBScript", "DevOps"],
    },
    {
      company: "SYSPRO Africa",
      location: "Sunninghill, South Africa",
      role: "Intern – SYSPRO Internship Program",
      period: "January 2019 – January 2020",
      description:
        "Developed a firm understanding of SYSPRO ERP and a wide spectrum of business skills covering manufacturing and distribution.",
      highlights: [
        "Learned Enterprise Resource Planning concepts across supply chain, manufacturing, and distribution",
      ],
      technologies: [
        "SYSPRO 8",
        "ERP",
        "Supply Chain",
        "Manufacturing",
        "Distribution",
      ],
    },
    {
      company: "Future Front Web",
      location: "Johannesburg, South Africa",
      role: "Freelance Web Developer",
      period: "June 2017 – January 2019",
      description:
        "Developed and maintained backend systems for various websites, ensuring security and reliability.",
      highlights: [
        "Collaborated with clients to deliver tailored solutions, exceeding expectations in functionality and usability",
      ],
      technologies: [
        "PHP",
        "HTML",
        "CSS",
        "Bootstrap",
        "JavaScript",
        "jQuery",
      ],
    },
  ],
  education: {
    institution: "Belgium Campus IT University",
    location: "Pretoria, Gauteng, South Africa",
    degree: "Bachelor's Degree of Computing (B.Comp.)",
    level: "NQF Level 8",
    coursework: [
      "Software Project Management",
      "Software Analysis & Design",
      "Software Engineering",
      "Database Development",
      "Web Development",
      "Android Development",
      "Object Oriented Programming",
      "Hardware Programming",
      "Computer Networks",
      "Internet Systems",
      "Information Systems",
      "Computer Security",
      "Applied Mathematics",
      "Calculus",
      "Statistics",
      "Operations Research",
    ],
  },
  certificates: [
    {
      name: "ISTQB Certified Tester Foundation Level",
      year: "2025",
      issuer: "ISTQB",
    },
    { name: "Angular 17", year: "2024", issuer: "Engineering" },
    { name: "C# Fundamentals", year: "2024", issuer: "Engineering" },
    { name: "Web3 DAPP Development", year: "2024", issuer: "Engineering" },
    {
      name: "Certified Blockchain Architect",
      year: "2023",
      issuer: "Engineering",
    },
    {
      name: "Certified Blockchain Expert",
      year: "2022",
      issuer: "Engineering",
    },
    {
      name: "Blockchains & Ethereum: Introduction",
      year: "2022",
      issuer: "Engineering",
    },
    {
      name: "Google Analytics for Beginners",
      year: "2021",
      issuer: "Google",
    },
    {
      name: "Premium Developer Consultant Certification L1",
      year: "2019",
      issuer: "SYSPRO",
    },
    {
      name: "Premium Support Consultant Distribution Certification L1",
      year: "2019",
      issuer: "SYSPRO",
    },
    {
      name: "Premium Implementation Consultant Distribution Certification L1",
      year: "2019",
      issuer: "SYSPRO",
    },
    { name: "Business Life Skills", year: "2019", issuer: "The Learning Revolution" },
    { name: "Effective Writing", year: "2019", issuer: "The Learning Revolution" },
    {
      name: "Successful Presentations for Business",
      year: "2019",
      issuer: "The Learning Revolution",
    },
  ],
};
